## Učitati skup podataka 

In [806]:
import pandas as pd
import numpy as np

In [807]:
bank=pd.read_csv('C:\\Users\\Dusica\\Downloads\\Bank Marketing\\bank-additional.txt',sep=';')

## Deskriptivna statistika skupa podataka 

In [808]:
bank.shape


(4119, 21)

In [809]:
bank.describe()

age     duration     campaign        pdays     previous  \
count  4119.000000  4116.000000  4114.000000  4119.000000  4117.000000   
mean     40.113620   256.869048     2.534273   960.422190     0.190430   
std      10.313362   254.763913     2.566673   191.922786     0.541904   
min      18.000000     0.000000     1.000000     0.000000     0.000000   
25%      32.000000   103.000000     1.000000   999.000000     0.000000   
50%      38.000000   181.000000     2.000000   999.000000     0.000000   
75%      47.000000   317.250000     3.000000   999.000000     0.000000   
max      88.000000  3643.000000    35.000000   999.000000     6.000000   

       emp.var.rate  cons.price.idx  cons.conf.idx    euribor3m  
count   4116.000000     4117.000000    4117.000000  4117.000000  
mean       0.084694       93.579540     -40.486358     4.858993  
std        1.563361        0.579442       4.639840    79.432456  
min       -3.400000       92.201000     -50.800000     0.635000  
25%       -1.800000       93.075000     -42.700000     1.334000  
50%        1.100000       93.749000     -41.800000     4.857000  
75%        1.400000       93.994000     -36.400000     4.961000  
max        1.400000       94.767000       1.266000  5099.100000

In [810]:
bank.select_dtypes(include=['object']).describe()

job  marital          education default housing  loan   contact  \
count     4119     4119               4119    4119    4119  4119      4119   
unique      12        4                  8       3       3     3         2   
top     admin.  married  university.degree      no     yes    no  cellular   
freq      1012     2509               1264    3315    2175  3349      2652   

       month day_of_week     poutcome nr.employed     y  
count   4119        4119         4119        4118  4118  
unique    10           5            3          12     2  
top      may         thu  nonexistent      5228.1    no  
freq    1378         860         3523        1625  3667

In [811]:
pd.concat([bank.dtypes,bank.isnull().sum()],axis=1)

0  1
age               int64  0
job              object  0
marital          object  0
education        object  0
default          object  0
housing          object  0
loan             object  0
contact          object  0
month            object  0
day_of_week      object  0
duration        float64  3
campaign        float64  5
pdays             int64  0
previous        float64  2
poutcome         object  0
emp.var.rate    float64  3
cons.price.idx  float64  2
cons.conf.idx   float64  2
euribor3m       float64  2
nr.employed      object  1
y                object  1

## Priprema skupa podataka
(tako da bude pogodan za prediktivno modelovanje)

Input(duration) should only be included for benchmark purposes and should be discarded if the intention is to have a realistic predictive model.

In [812]:
bank.drop(['duration'],axis=1,inplace=True)

### *Resavanje null vrednosti*

In [813]:
bank.dropna(subset=['y'],inplace=True)

In [814]:
#set(bank['nr.employed'])

In [815]:
pd.concat([bank['cons.price.idx'].describe(),bank['previous'].describe()],axis=1)

#moze mean jer std ima malu vrednost

cons.price.idx     previous
count     4116.000000  4116.000000
mean        93.579707     0.190476
std          0.579413     0.541961
min         92.201000     0.000000
25%         93.075000     0.000000
50%         93.749000     0.000000
75%         93.994000     0.000000
max         94.767000     6.000000

In [816]:
mean_cons_price_idx=bank['cons.price.idx'].dropna().mean()
#mean_cons_price_idx=np.average(bank['cons.price.idx'].dropna())

In [817]:
mean_previous=bank['previous'].dropna().mean()

In [818]:
bank['cons.price.idx'].replace(np.nan,mean_cons_price_idx,inplace=True)

In [819]:
bank['previous'].replace(np.nan,mean_previous,inplace=True)

In [820]:
bank['nr.employed']=pd.to_numeric(bank['nr.employed'],downcast='float')

In [821]:
bank['nr.employed'].fillna(value=bank['nr.employed'].dropna().mean(),inplace=True)

In [822]:
bank['nr.employed'].describe()

count    4118.000000
mean     5166.518555
std        73.662903
min      4963.600098
25%      5099.100098
50%      5191.000000
75%      5228.100098
max      5228.100098
Name: nr.employed, dtype: float64

campaign	float64	5
emp.var.rate	float64	3
cons.conf.idx	float64	2
euribor3m	float64	2

In [823]:
pd.concat([bank['campaign'].describe(),bank['emp.var.rate'].describe(),bank['cons.conf.idx'].describe(),bank['euribor3m'].describe()],axis=1)

campaign  emp.var.rate  cons.conf.idx    euribor3m
count  4113.000000   4115.000000    4116.000000  4116.000000
mean      2.533917      0.085152     -40.496501     3.621325
std       2.566883      1.563274       4.594520     1.733618
min       1.000000     -3.400000     -50.800000     0.635000
25%       1.000000     -1.800000     -42.700000     1.334000
50%       2.000000      1.100000     -41.800000     4.857000
75%       3.000000      1.400000     -36.400000     4.961000
max      35.000000      1.400000     -26.900000     5.045000

In [824]:
bank['campaign'].replace(np.nan,bank['campaign'].dropna().mean(),inplace=True)

In [825]:
bank['emp.var.rate'].replace(np.nan,bank['emp.var.rate'].dropna().mean(),inplace=True)

In [826]:
bank['cons.conf.idx'].replace(np.nan,bank['cons.conf.idx'].dropna().mean(),inplace=True)

In [827]:
bank['euribor3m'].replace(np.nan,bank['euribor3m'].dropna().mean(),inplace=True)

Diskretizacija klasifikatora

In [ ]:
bank['y'] = np.where(bank['y']=='no', 0, 1)

eliminate categorical variables from sample

In [590]:
bank_without_cat=bank.select_dtypes(exclude=['object'])

## Podela skupa podataka na trening i test u odnosu 70:30

In [591]:
def split_train_test(bank, test_percentage, shuffle=True):
    df=bank.sample(frac=1)
    n=len(df)
    split=int(np.floor(n*test_percentage))
    test= df.iloc[:split,:]
    train=df.iloc[split:,:]
    return (train, test)

In [592]:
#from sklearn.model_selection import train_test_split
#drugi nacin, ali ista stvar;identicno radi

In [593]:
train,test=split_train_test(bank,0.3)


In [594]:
train.shape

(2883, 20)

In [595]:
test.shape

(1235, 20)

In [596]:
y_train=train['y']
#y_train=train.loc[:,'y']

In [597]:
y_train.shape

(2883,)

In [598]:
x_train=train.drop('y',axis=1).select_dtypes(exclude=['object'])

In [599]:
x_train.shape

(2883, 9)

In [600]:
x_test=test.drop('y',axis=1).select_dtypes(exclude=['object'])

In [601]:
y_test=test['y']

Kreirati minimalno 2 prediktivna modela (sa default parametrima) i oceniti gresku na test setu (minimum 2 mere evaluacije)

# Logistic regression

In [603]:
from sklearn.linear_model import LogisticRegression

In [604]:
lr=LogisticRegression()

In [605]:
modelLR=lr.fit(x_train,y_train)

In [606]:
predictionsLR=modelLR.predict(x_test)

In [804]:
predict_train=modelLR.predict(x_train)

array([0, 1, 0, ..., 0, 0, 0])

In [805]:
prediction_probs=modelLR.predict_proba(x_test)
prediction_probs

array([[ 0.94717197,  0.05282803],
       [ 0.93680629,  0.06319371],
       [ 0.96138595,  0.03861405],
       ..., 
       [ 0.957783  ,  0.042217  ],
       [ 0.18479833,  0.81520167],
       [ 0.96566792,  0.03433208]])

In [616]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

In [802]:
print('ACCURACY')
print('Train')
print(accuracy_score(y_train,predict_train))
print('Test')
print(accuracy_score(y_test,predictionsLR))

ACCURACY
Train
0.901838362817
Test
0.902834008097


In [803]:
print('        Precision'+'     '+'   Recall')
print('Train  ',precision_score(y_train,predict_train),'  ',recall_score(y_train,predict_train))
print('Test   ',precision_score(y_test,predictionsLR),'      ','    ' ,recall_score(y_test,predictionsLR))

        Precision        Recall
Train   0.688679245283    0.22600619195
Test    0.625             0.15625


In [619]:
print('CONFUSION MATRIX')
print('Train')
confusion_matrix(y_train, predict_train)

CONFUSION MATRIX
Train


array([[2527,   33],
       [ 250,   73]], dtype=int64)

In [620]:
y_train.value_counts()

0    2560
1     323
Name: y, dtype: int64

In [621]:
print('CONFUSION MATRIX')
print('Test')
confusion_matrix(y_test, predictionsLR)

CONFUSION MATRIX
Test


array([[1095,   12],
       [ 108,   20]], dtype=int64)

In [622]:
y_test.value_counts()

0    1107
1     128
Name: y, dtype: int64

# Random Forest

In [623]:
from sklearn.ensemble import RandomForestClassifier

In [624]:
rf=RandomForestClassifier()

In [625]:
modelRF=rf.fit(x_train,y_train)

In [626]:
predictionsRF_train=modelRF.predict(x_train)

In [627]:
predictionsRF=modelRF.predict(x_test)

In [738]:
confusion_matrix(y_test,predictionsRF)

array([[1068,   39],
       [  99,   29]], dtype=int64)

In [633]:
print('           Accuracy   '+'        Precision'+'     '+'   Recall')
print('Train  ',' ',accuracy_score(y_train,predictionsRF_train),'   ',precision_score(y_train,predictionsRF_train),' ',recall_score(y_train,predictionsRF_train))
print('Test   ',' ',accuracy_score(y_test,predictionsRF),'    ',precision_score(y_test,predictionsRF),' ',recall_score(y_test,predictionsRF))


           Accuracy           Precision        Recall
Train     0.973291710024     0.965909090909   0.789473684211
Test      0.888259109312      0.426470588235   0.2265625


# KNeighborsClassifier

In [634]:
from sklearn.neighbors import KNeighborsClassifier

In [635]:
knn=KNeighborsClassifier()

In [636]:
modelknn=knn.fit(x_train, y_train)

In [637]:
predictionsKNN_train=knn.predict(x_train)

In [638]:
predictionsKNN=knn.predict(x_test)

In [639]:
prediction_probs_knn=knn.predict_proba(x_test)

In [643]:
print('           Accuracy   '+'        Precision'+'     '+'   Recall')
print('Train  ',' ',accuracy_score(y_train,predictionsKNN_train),'   ',precision_score(y_train,predictionsKNN_train),' ',recall_score(y_train,predictionsKNN_train))
print('Test   ',' ',accuracy_score(y_test,predictionsKNN),'   ',precision_score(y_test,predictionsKNN),' ',recall_score(y_test,predictionsKNN))


           Accuracy           Precision        Recall
Train     0.909816163718     0.714285714286   0.325077399381
Test      0.901214574899     0.555555555556   0.234375


### Cross validation

In [644]:
from sklearn.model_selection import cross_val_score

In [835]:
models=[lr,rf,knn]

In [836]:
for mod in models:
    print (mod)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)
RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)
KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')


In [837]:
for num in range(len(models)):
    scores=cross_val_score(models[num-1],x_train,y_train,cv=5,scoring='accuracy')
    print (scores,'--->',scores.mean())

[ 0.89428076  0.87694974  0.90121317  0.88715278  0.89583333] ---> 0.891085957058
[ 0.89948007  0.89948007  0.90814558  0.89756944  0.90451389] ---> 0.901837810514
[ 0.89948007  0.85441941  0.89428076  0.87326389  0.89236111] ---> 0.882761048527


In [838]:
for num in range(len(models)):
    scores=cross_val_score(models[num-1],x_test,y_test,cv=5,scoring='accuracy')
    print (scores,'--->',scores.mean())
#np.average(scores)

[ 0.89919355  0.88306452  0.90283401  0.8699187   0.88617886] ---> 0.888237926718
[ 0.90322581  0.88709677  0.90283401  0.89430894  0.91463415] ---> 0.900419935635
[ 0.875       0.87096774  0.87854251  0.8699187   0.88617886] ---> 0.876121562607


## Optimizacija parametara

In [650]:
from sklearn.model_selection import GridSearchCV

In [651]:
rf

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [652]:
params = [
  {'n_estimators': [10, 20, 40, 100, 300, 400], 'max_depth': [1, 5, 10, 15]}
 ]

In [653]:
optimizer = GridSearchCV(rf, 
                   param_grid=params, 
                         cv=3,  
                   return_train_score=True)

In [654]:
opt_rf=optimizer.fit(x_train,y_train)

In [782]:
opt_rf.best_estimator_
#n_estimators=100 i max_depth=5

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=5, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [656]:
probas_opt=opt_rf.predict_proba(x_test)

In [657]:
predictions_opt=opt_rf.predict(x_test)

In [783]:
lr

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [784]:
knn

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [660]:
params2 = [
  {'leaf_size': [10, 20, 40, 50, 100], 'n_neighbors': [1, 2, 3, 4, 5, 6, 7]}
 ]

In [661]:
optimizer2 = GridSearchCV(knn, 
                   param_grid=params2, 
                         cv=3,  
                   return_train_score=True)

In [662]:
opt_rf2=optimizer2.fit(x_train,y_train)

In [663]:
opt_rf2.best_estimator_
#leaf_size=20, n_neighbors=4,

KNeighborsClassifier(algorithm='auto', leaf_size=20, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=4, p=2,
           weights='uniform')

In [664]:
probas_opt_knn=opt_rf2.predict_proba(x_test)
predictions_opt_knn=opt_rf2.predict(x_test)

## Parameter optimization - Results
### Random Forest 

In [666]:
print('ACCURACY\n','Before',accuracy_score(y_test,predictionsRF),'\n After ',accuracy_score(y_test,predictions_opt))

ACCURACY
 Before 0.888259109312 
 After  0.898785425101


In [667]:
print('PRECISION\n Before',precision_score(y_test,predictionsRF),'\n After ',precision_score(y_test,predictions_opt))

PRECISION
 Before 0.426470588235 
 After  0.555555555556


In [668]:
print('RECALL\n Before',recall_score(y_test,predictionsRF),'\n After ',recall_score(y_test,predictions_opt))

RECALL
 Before 0.2265625 
 After  0.1171875


### KNN 

In [669]:
print('Accuracy')
print('Before',accuracy_score(y_test,predictionsKNN),'\nAfter ',accuracy_score(y_test,predictions_opt_knn))

Accuracy
Before 0.901214574899 
After  0.8995951417


In [670]:
print('Precision')
print('Before',precision_score(y_test,predictionsKNN),'\nAfter ',precision_score(y_test,predictions_opt_knn))

Precision
Before 0.555555555556 
After  0.558823529412


In [683]:
print('Recall')
print('Before',recall_score(y_test,predictionsKNN),'\nAfter ',recall_score(y_test,predictions_opt_knn))

Recall
Before 0.234375 
After  0.1484375


### Podela inicijalnog skupa podataka na osnovu jednog kategoričkog atributa u datasetu

In [847]:
#for n in range(len(categories)):
 #   listaDF.append(bank.loc[lambda bank:bank['loan']==categories[n]])

In [848]:
categories=bank.loan.unique()
listaDF=[]
for rb in range(len(listaDF)):

    scores=cross_val_score(rf,listaDF[rb].drop('y',axis=1).select_dtypes(exclude=['object']),listaDF[rb]['y'],cv=5,scoring='accuracy')
    print (len(listaDF[rb].loan),listaDF[rb].loan.unique(),scores,'--->',scores.mean())
    

In [849]:
listaDF=[]
categories=bank.housing.unique()
for n in range(len(categories)):
     listaDF.append(bank.loc[lambda bank:bank['housing']==categories[n]])

In [850]:
for rb in range(len(listaDF)):
    scores=cross_val_score(rf,listaDF[rb].drop('y',axis=1).select_dtypes(exclude=['object']),listaDF[rb]['y'],cv=5,scoring='roc_auc')
    print(len(listaDF[rb].housing),listaDF[rb].housing.unique(),scores,'--->',scores.mean())


2175 ['yes'] [ 0.73557278  0.69842808  0.77096792  0.67536068  0.75697136] ---> 0.727460163652
1838 ['no'] [ 0.66608418  0.71056165  0.75764526  0.69827982  0.79006116] ---> 0.724526412304
105 ['unknown'] [ 0.7125      0.71052632  0.68421053  0.97368421  0.94736842] ---> 0.805657894737


In [854]:
bank['marital'].value_counts()
#married

bank['marital'].replace('unknown','married',inplace=True)
categories=bank.marital.unique()
listaDF=[]
for n in range(len(categories)):
    #listaDF.append(pd.DataFrame)
    listaDF.append(bank.loc[lambda bank:bank['marital']==categories[n]])
for rb in range(len(listaDF)):
    scores=cross_val_score(rf,listaDF[rb].drop('y',axis=1).select_dtypes(exclude=['object']),listaDF[rb]['y'],cv=5,scoring='roc_auc')
    print(len(listaDF[rb].marital),listaDF[rb].marital.unique(),scores,'--->',scores.mean())
 

2519 ['married'] [ 0.68916818  0.66904731  0.68488941  0.69487859  0.77602649] ---> 0.702801994744
1153 ['single'] [ 0.74758065  0.65903226  0.70580645  0.6964662   0.744367  ] ---> 0.710650510618
446 ['divorced'] [ 0.73045267  0.68038409  0.8223594   0.67734375  0.659375  ] ---> 0.713982981824


## Recursive feature elimination

In [801]:
# Feature Extraction with RFE
from sklearn.feature_selection import RFE
 
#feature extraction
rfe = RFE(lr, 4)
fit = rfe.fit(x_train, y_train)
print("Number of Features:",  fit.n_features_)
print("Selected Features:" , fit.support_)
print("Feature Ranking::" , fit.ranking_)

#atributi=[x_train.columns]
#prediktivnaMoc=[fit.ranking_]
#print(atributi)
#print(prediktivnaMoc)

    #campaign, previous, euribor3m za 
    #emp.var.rate
#BOlJE je lr jer je overfit za rf???

Number of Features: 4
Selected Features: [False  True False  True  True False False  True False]
Feature Ranking:: [4 1 6 1 1 3 2 1 5]


In [798]:
predictions_rfe=fit.predict(x_test)

In [799]:
predictions_rfe_train=fit.predict(x_train)

In [800]:
print('           Accuracy   '+'        Precision'+'     '+'   Recall')
print('Train  ',' ',accuracy_score(y_train,predictions_rfe_train),'   ',precision_score(y_train,predictions_rfe_train),'  ',recall_score(y_train,predictions_rfe_train))
print('Test   ',' ',accuracy_score(y_test,predictions_rfe),'   ',precision_score(y_test,predictions_rfe),'           ',recall_score(y_test,predictions_rfe))


           Accuracy           Precision        Recall
Train     0.892126257371     0.676470588235    0.0712074303406
Test      0.897975708502     0.625             0.0390625


In [793]:
#Logistic regression pre selekcije atributa---->na celom datasetu

print('        Precision'+'     '+'   Recall')
print('Train  ',precision_score(y_train,predict_train),'  ',recall_score(y_train,predict_train))
print('Test   ',precision_score(y_test,predictionsLR),'      ','    ' ,recall_score(y_test,predictionsLR))


        Precision        Recall
Train   0.688679245283    0.22600619195
Test    0.625             0.15625


In [786]:
#random forest
#print('           Accuracy   '+'        Precision'+'     '+'   Recall')
#print('Train  ',' ',accuracy_score(y_train,predictionsRF_train),'   ',precision_score(y_train,predictionsRF_train),' ',recall_score(y_train,predictionsRF_train))
#print('Test   ',' ',accuracy_score(y_test,predictionsRF),'    ',precision_score(y_test,predictionsRF),' ',recall_score(y_test,predictionsRF))


           Accuracy           Precision        Recall
Train     0.973291710024     0.965909090909   0.789473684211
Test      0.888259109312      0.426470588235   0.2265625


In [ ]:
#manje sa LR

In [ ]:
#Na kom podskupu dobijate najbolje performanse predikcije? 

#Kako se razlikuju performanse na kompletnom test setu i na parcijalnim. 

#Koji atributi imaju najveću prediktivnu moć. 
#campaign, previous, euribor3m rf i emp.var.rate---ali je tu preucen
 #Kako se razlikuju performanse modela sa optimizovanim parametrima u odnosu na modele sa default parametrima? 
#Poboljsao se precision malo,i accuracy kod RF i LR

#Da li mislite da bi neka druga kombinacija parametara bila bolja za vaš dataset (i zašto). 

#Da li su vaši modeli pretrenirani (overfit)?—
#random forest jeste